name: flutter_nsd
description: A Flutter plugin for Network Service Discovery (mDNS) on Android, iOS, MacOS and Windows. The plugin uses the platform's own API when possible. Supports discovery only, no registry.
version: 1.3.0
homepage: https://github.com/Nimrodda/flutter_nsd

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nimroddayan.flutternsd
        pluginClass: FlutterNsdPlugin
      ios:
        pluginClass: SwiftFlutterNsdPlugin
      macos:
        pluginClass: SwiftFlutterNsdPlugin
      windows:
        fileName: flutter_nsd_plugin.cpp
        pluginClass: FlutterNsdPlugin
