name: flutter_nsd

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub get
        working-directory: example
      - run: flutter build apk
        working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: |
            example/build/app/outputs/flutter-apk/app-release.apk
