name: flutter_nsd

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub get
        working-directory: example
      - run: flutter build ios --release --no-codesign
        working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: ios-build
          path: |
            example/build/ios/iphoneos/Runner.app
