name: flutter_nsd

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter config --enable-macos-desktop
        working-directory: example
      - run: flutter build macos
        working-directory: example
      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            example/build/macos/Build/Products/Release/flutter_nsd_example.app
